# Generated by Django 3.1.7 on 2023-03-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Caption', max_length=60)),
                ('thumbnail', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
