# Generated by Django 3.1.7 on 2023-03-15 04:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230315_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('thumb', models.ImageField(upload_to='eventthumb')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('author', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='no-slug', max_length=200, unique=True)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
